//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 03:39:13 PM IST 
//


package com.taskmanager.domain;

import java.util.List;


public class ContactStatus {

    protected List<String> mobilenumbers;
    protected String regstatus;
	public List<String> getMobilenumbers() {
		return mobilenumbers;
	}
	public void setMobilenumbers(List<String> mobilenumbers) {
		this.mobilenumbers = mobilenumbers;
	}
	public String getRegstatus() {
		return regstatus;
	}
	public void setRegstatus(String regstatus) {
		this.regstatus = regstatus;
	}

   

}
