//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 04:56:55 PM IST 
//


package com.taskmanager.domain;



/**
 * <p>Java class for MessageInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="assignFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assignFromName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assignTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assignToName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createdTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="messageDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class MessageInfoType {
	
	private String transactionId;
	private String isMessageRead;

	private String oldMessageId;
    protected Long messageId;
    
    protected String assignFrom;
    
    protected String assignFromName;
    
    protected String assignTo;
    
    protected String assignToName;
    
    protected String createdTime;

    protected Long taskId;
    
    protected String messageDescription;
    

    public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getIsMessageRead() {
		return isMessageRead;
	}

	public void setIsMessageRead(String isMessageRead) {
		this.isMessageRead = isMessageRead;
	}

	/**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMessageId(Long value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the assignFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignFrom() {
        return assignFrom;
    }

    /**
     * Sets the value of the assignFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignFrom(String value) {
        this.assignFrom = value;
    }

    /**
     * Gets the value of the assignFromName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignFromName() {
        return assignFromName;
    }

    /**
     * Sets the value of the assignFromName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignFromName(String value) {
        this.assignFromName = value;
    }

    /**
     * Gets the value of the assignTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignTo() {
        return assignTo;
    }

    /**
     * Sets the value of the assignTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignTo(String value) {
        this.assignTo = value;
    }

    /**
     * Gets the value of the assignToName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignToName() {
        return assignToName;
    }

    /**
     * Sets the value of the assignToName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignToName(String value) {
        this.assignToName = value;
    }

    /**
     * Gets the value of the createdTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * Sets the value of the createdTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedTime(String value) {
        this.createdTime = value;
    }

    /**
     * Gets the value of the taskId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * Sets the value of the taskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTaskId(Long value) {
        this.taskId = value;
    }

    /**
     * Gets the value of the messageDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageDescription() {
        return messageDescription;
    }

    /**
     * Sets the value of the messageDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageDescription(String value) {
        this.messageDescription = value;
    }

	public String getOldMessageId() {
		return oldMessageId;
	}

	public void setOldMessageId(String oldMessageId) {
		this.oldMessageId = oldMessageId;
	}

}
