//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 03:39:13 PM IST 
//


package com.taskmanager.domain;

import java.util.List;




public class RegistrationStatus {

   
    protected List<ContactStatus> contactList;
   
    protected String status;

	public List<ContactStatus> getContactList() {
		return contactList;
	}

	public void setContactList(List<ContactStatus> contactList) {
		this.contactList = contactList;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

   
}
