//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.16 at 10:18:13 AM IST 
//


package com.taskmanager.domain;


public class SyncTask {

    
   
    
    protected SysncTaskResponseType response;

    

    public SysncTaskResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link SysncTaskResponseType }
     *     
     */
    public void setResponse(SysncTaskResponseType value) {
        this.response = value;
    }

}
