//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.16 at 10:18:13 AM IST 
//


package com.taskmanager.domain;



public class SysncTaskResponseType {

   
    protected TaskResponseListType tasks;

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link TaskResponseListType }
     *     
     */
    public TaskResponseListType getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskResponseListType }
     *     
     */
    public void setTasks(TaskResponseListType value) {
        this.tasks = value;
    }

}
