//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 04:56:55 PM IST 
//


package com.taskmanager.domain;

import java.util.List;



public class TaskResponseListType {

    private List<TaskInfoType> task;

	public List<TaskInfoType> getTask() {
		return task;
	}

	public void setTask(List<TaskInfoType> task) {
		this.task = task;
	}
   
   /* protected List<ChangedAssigneeType> changedAssignies;
   
    protected String lastUpdateTime;

	public List<TaskInfoType> getTask() {
		return task;
	}

	public void setTask(List<TaskInfoType> task) {
		this.task = task;
	}

	public List<ChangedAssigneeType> getChangedAssignies() {
		return changedAssignies;
	}

	public void setChangedAssignies(List<ChangedAssigneeType> changedAssignies) {
		this.changedAssignies = changedAssignies;
	}

	public String getLastUpdateTime() {
		return lastUpdateTime;
	}

	public void setLastUpdateTime(String lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}*/

    

}
