//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 04:56:55 PM IST 
//


package com.taskmanager.domain;



public class Task {

  
   
    private TaskResponseType response;

	public TaskResponseType getResponse() {
		return response;
	}

	public void setResponse(TaskResponseType response) {
		this.response = response;
	}

    

}
